services:
  decidim-user_fields:
    container_name: decidim-user_fields
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.29
    entrypoint: ""
    volumes:
      - .:/home/decidim/module
      - bundle:/home/decidim/app/vendor
      - node_modules:/home/decidim/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@user-fields-pg:5432/decidim
      - DECIDIM_VERSION=0.29.4
      - DEV_MODULE=decidim-user_fields
      - RAILS_ENV=development
    ports:
      - 3000:3000
    links:
      - user-fields-pg
    depends_on:
      - user-fields-pg

  user-fields-pg:
    container_name: user-fields-pg
    image: postgres:16
    volumes:
      - user_fields-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=decidim
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe

volumes:
  node_modules: {}
  bundle: {}
  user_fields-pg-data: {}
